#!/usr/bin/env tsx
/**
 * Interactive setup: prompts for required env vars and writes .env.local.
 * Run: pnpm setup
 */

import * as fs from "fs"
import * as readline from "readline"

const ENV_PATH = ".env.local"

function ask(
  rl: readline.Interface,
  question: string,
  defaultVal = ""
): Promise<string> {
  const prompt = defaultVal ? `${question} [${defaultVal}]: ` : `${question}: `
  return new Promise(resolve => {
    rl.question(prompt, answer => {
      resolve((answer || defaultVal).trim())
    })
  })
}

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  console.log("\n🔧 Albuc – Environment setup\n")
  console.log(
    "Enter values for .env.local. Press Enter to use the default where shown.\n"
  )

  const siteUrl = await ask(
    rl,
    "Site URL (for auth redirects)",
    "http://localhost:3000"
  )
  const supabaseUrl = await ask(
    rl,
    "Supabase project URL",
    "https://xxx.supabase.co"
  )
  const supabaseAnon = await ask(rl, "Supabase anon key", "")
  const databaseUrl = await ask(
    rl,
    "Database URL (Supabase connection string)",
    ""
  )

  console.log("\n--- AI provider ---")
  console.log("Options: google | openai | anthropic")
  const aiProvider = await ask(rl, "AI provider (chat)", "google")

  let aiKey = ""
  if (aiProvider === "google") {
    aiKey = await ask(rl, "GOOGLE_GENERATIVE_AI_API_KEY", "")
  } else if (aiProvider === "openai") {
    aiKey = await ask(rl, "OPENAI_API_KEY", "")
  } else if (aiProvider === "anthropic") {
    aiKey = await ask(rl, "ANTHROPIC_API_KEY", "")
  }

  const chatModel = await ask(
    rl,
    "AI chat model (optional, provider default if empty)",
    ""
  )
  const embeddingProvider = await ask(
    rl,
    "Embedding provider (google | openai, default: google)",
    "google"
  )
  const embeddingModel = await ask(rl, "Embedding model (optional)", "")

  let openaiKeyForEmbedding = ""
  if (embeddingProvider === "openai" && aiProvider !== "openai") {
    openaiKeyForEmbedding = await ask(rl, "OPENAI_API_KEY (for embeddings)", "")
  }

  rl.close()

  const lines: string[] = [
    "# Generated by pnpm setup",
    "",
    "NEXT_PUBLIC_SITE_URL=" +
      (siteUrl ? `"${siteUrl}"` : '"http://localhost:3000"'),
    "",
    "NEXT_PUBLIC_SUPABASE_URL=" + (supabaseUrl ? `"${supabaseUrl}"` : '""'),
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=" +
      (supabaseAnon ? `"${supabaseAnon}"` : '""'),
    "DATABASE_URL=" + (databaseUrl ? `"${databaseUrl}"` : '""'),
    "",
    "AI_PROVIDER=" + (aiProvider || "google"),
  ]

  if (chatModel) lines.push("AI_CHAT_MODEL=" + chatModel)
  if (embeddingProvider)
    lines.push("AI_EMBEDDING_PROVIDER=" + embeddingProvider)
  if (embeddingModel) lines.push("AI_EMBEDDING_MODEL=" + embeddingModel)

  if (aiProvider === "google" && aiKey)
    lines.push("GOOGLE_GENERATIVE_AI_API_KEY=" + aiKey)
  else if (aiProvider === "openai" && aiKey)
    lines.push("OPENAI_API_KEY=" + aiKey)
  else if (aiProvider === "anthropic" && aiKey)
    lines.push("ANTHROPIC_API_KEY=" + aiKey)

  if (
    embeddingProvider === "openai" &&
    (aiProvider === "openai" ? aiKey : openaiKeyForEmbedding)
  ) {
    if (aiProvider !== "openai")
      lines.push("OPENAI_API_KEY=" + openaiKeyForEmbedding)
  }

  lines.push("")

  fs.writeFileSync(ENV_PATH, lines.join("\n"), "utf8")
  console.log("\n✅ Wrote " + ENV_PATH)

  console.log("\nNext steps:")
  console.log("  1. pnpm install")
  console.log(
    "  2. In Supabase: enable pgvector: CREATE EXTENSION IF NOT EXISTS vector;"
  )
  console.log("  3. pnpm db:push")
  console.log("  4. pnpm dev")
  console.log("\nDeploy to Vercel:")
  console.log("  • Install Vercel CLI: npm i -g vercel")
  console.log("  • Run: vercel")
  console.log(
    "  • Add the same env vars in Vercel dashboard (Settings → Environment Variables)"
  )
  console.log(
    "  • Set NEXT_PUBLIC_SITE_URL to your Vercel URL (e.g. https://your-app.vercel.app)"
  )
  console.log("")
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
